services:
  - type: web
    name: ai-health-companion
    env: node
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
